name: build
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test

  build:
    name: build
    needs: test

    permissions:
      packages: write

    uses: evanpurkhiser/workflows/.github/workflows/docker.yml@main
    with:
      publish: ${{ github.ref == 'refs/heads/main' }}
